import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "../css/btn.css"
import "../css/dialog.css"
import "../css/grid.css"
import "../css/input.css"
import "../css/main.css"
import "../css/table.css"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "my project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased container`}
      >
        {children}
      </body>
    </html>
  );
}
